# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

col_sums <- function(matty) {
    .Call(`_package1_col_sums`, matty)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_package1_RcppExport_registerCCallable', PACKAGE = 'package1')
})
