// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// col_sums
arma::vec col_sums(const arma::mat& test);
RcppExport SEXP _package2_col_sums(SEXP testSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type test(testSEXP);
    rcpp_result_gen = Rcpp::wrap(col_sums(test));
    return rcpp_result_gen;
END_RCPP
}
// col_sums_imported
arma::vec col_sums_imported(const arma::mat& test);
RcppExport SEXP _package2_col_sums_imported(SEXP testSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type test(testSEXP);
    rcpp_result_gen = Rcpp::wrap(col_sums_imported(test));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_package2_col_sums", (DL_FUNC) &_package2_col_sums, 1},
    {"_package2_col_sums_imported", (DL_FUNC) &_package2_col_sums_imported, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_package2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
