# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

col_sums <- function(test) {
    .Call(`_package2_col_sums`, test)
}

col_sums_imported <- function(test) {
    .Call(`_package2_col_sums_imported`, test)
}

col_sums_copy <- function(test) {
    .Call(`_package2_col_sums_copy`, test)
}

