// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/package1.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// col_sums_internal
arma::vec col_sums_internal(const arma::mat& matty);
RcppExport SEXP _package1_col_sums_internal(SEXP mattySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type matty(mattySEXP);
    rcpp_result_gen = Rcpp::wrap(col_sums_internal(matty));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_package1_col_sums_internal", (DL_FUNC) &_package1_col_sums_internal, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_package1(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
